--★Favorit 관련★--
--나의 찜목록
SELECT PIMAGE1,PTITLE FROM PRODUCT P, FAVORITE F WHERE P.PCODE=F.PCODE AND CID='aaa';
--찜하기
INSERT INTO FAVORITE (FCODE,CID,PCODE) VALUES (FAVORITE_SEQ.NEXTVAL,'aaa',2);
--찜 취소
DELETE FROM FAVORITE WHERE CID='aaa' AND FCODE='2';
--나의 찜 갯수
SELECT COUNT(*) FROM FAVORITE WHERE CID='aaa';
--상품의 찜 갯수
SELECT COUNT(*) FROM FAVORITE WHERE PCODE='2';
--★Product_Qna 관련★------
SELECT * FROM PRODUCT;
--상세
SELECT * FROM PRODUCT_QNA ORDER BY PQDATE DESC;
SELECT * FROM PRODUCT_QNA WHERE PQCODE='3';
--목록
SELECT * FROM (SELECT ROWNUM RN, A.* FROM 
		(SELECT * FROM PRODUCT_QNA WHERE PCODE='1' ORDER BY PQDATE DESC)A)
		WHERE RN BETWEEN 1 AND 10;
COMMIT;
--문의등록
INSERT INTO PRODUCT_QNA
		(pqcode,pqtitle,pqcontent,pqanswer,pqsecret,pqcomplete,pcode,cid)
		VALUES(PRODUCT_QNA_SEQ.nextval,'제목','내용','답변',0,0,1,'aaa');

--수정
UPDATE PRODUCT_QNA SET
		PQTITLE='제품질문',
		PQCONTENT='이거내용',
		PQANSWER='답변',
		PQSECRET=1,
		PQCOMPLETE=1
		WHERE PqCODE='1' AND CID='aaa';
--삭제
DELETE FROM PRODUCT_QNA WHERE PCODE='1' AND CID='aaa';
--Qna갯수
SELECT COUNT(*) FROM PRODUCT_QNA;
--★상품 관련★--
SELECT * FROM
    (SELECT ROWNUM RN ,A.* FROM
			(SELECT P.*,MNAME,(SELECT COUNT(*) FROM FAVORITE F,PRODUCT P 
                WHERE F.PCODE=P.PCODE)FAV FROM PRODUCT P, MARKET M
                    WHERE MNAME LIKE '%'||'롯'||'%' OR PTITLE LIKE '%'||'우'||'%' AND P.MID = M.MID ORDER BY FAV DESC)A)
        WHERE RN BETWEEN 1 AND 10;
--갯수
SELECT COUNT(*) FROM MARKET M, PRODUCT P WHERE MNAME LIKE '%'||'롯'||'%' OR PTITLE LIKE '%'||'우'||'%';
--상품상세
SELECT * FROM PRODUCT WHERE PCODE=1;
COMMIT;
--★주문목록 리스트 관련★--
--회원별
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM
        (SELECT SP.*,PO.*,ODCODE,CUID,ODCOUNT,ODUNIT FROM SP_ORDER SP, ORDER_DETAIL OD, PRODUCT_OPTION PO
			WHERE SP.OCODE=OD.OCODE AND OD.ODCODE=PO.POCODE 
                AND ONAME LIKE '%'||'P'||'%' ORDER BY ONAME)A)
        WHERE RN BETWEEN 1 AND 3;
COMMIT;
--상품별
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM
        (SELECT SP.*,PO.*,ODCODE,CUID,ODCOUNT,ODUNIT FROM SP_ORDER SP, ORDER_DETAIL OD, PRODUCT_OPTION PO
			WHERE SP.OCODE=OD.OCODE AND OD.ODCODE=PO.POCODE 
                AND PONAME LIKE '%'||'우'||'%' ORDER BY ONAME)A)
        WHERE RN BETWEEN 1 AND 3;
--마켓별
--먼저 마켓의 정보를 뿌린다
SELECT * FROM
    (SELECT ROWNUM RN ,A.* FROM
        (SELECT MID,MNAME, MTEL, MADDR1 FROM MARKET ORDER BY MNAME)A)
    WHERE RN BETWEEN 1 AND 5;
--그 후에 그 마켓의 주문 리스트
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM
        (SELECT SP.*,PO.*,ODCODE,CUID,ODCOUNT,ODUNIT FROM SP_ORDER SP, ORDER_DETAIL OD, PRODUCT_OPTION PO,MARKET M
			WHERE SP.OCODE=OD.OCODE AND OD.ODCODE=PO.POCODE 
                AND PCODE IN (SELECT PCODE FROM PRODUCT P,MARKET M WHERE P.MID=M.MID) ORDER BY ONAME)A)
        WHERE RN BETWEEN 1 AND 3;
--★공지사항 관련★--   
SELECT * FROM NOTICE order by ngroup desc, nstep;
--등록
INSERT INTO NOTICE (NCODE,NTITLE,NCONTENT,NGROUP,NSTEP,NINDENT,NHIT)
    VALUES (NOTICE_SEQ.NEXTVAL,'제목','내용',NOTICE_SEQ.CURRVAL,0,0,0);
--공지사항에 대한 답변글 관련--
--회원일때 --
INSERT INTO NOTICE (NCODE,NTITLE,NCONTENT,NGROUP,NSTEP,NINDENT,NHIT,CID)
    VALUES (NOTICE_SEQ.NEXTVAL,'제목','내용',4,1,1,0,'bbb');
--관리자 일때
INSERT INTO NOTICE (NCODE,NTITLE,NCONTENT,NGROUP,NSTEP,NINDENT,NHIT,AID)
    VALUES (NOTICE_SEQ.NEXTVAL,'제목','내용',4,1,1,0,'aaa');
--들여쓰기
UPDATE NOTICE SET NSTEP=NSTEP+1 WHERE NGROUP='4' AND NSTEP>0;
--조회수 올리기
UPDATE NOTICE SET NHIT=NHIT+1 WHERE NCODE='4';
--수정을 위한 공지사항 글 가져오기
SELECT * FROM NOTICE WHERE NCODE='4';
--수정
UPDATE NOTICE SET NTITLE='제목',          
                  NCONTENT='내용'
    WHERE NCODE='3';
--삭제
DELETE FROM NOTICE WHERE NCODE='3';
COMMIT;
--목록
SELECT * FROM 
    (SELECT ROWNUM RN, A.* FROM
        (SELECT * FROM NOTICE ORDER BY NGROUP DESC ,NSTEP)A)
    WHERE RN BETWEEN 1 AND 10;
--공지시항 갯수
SELECT COUNT(*) FROM NOTICE;
COMMIT;

















